version: 2.1

jobs:
  development:
    docker:
      - image: 'cimg/node:17.9.0'
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a yarn.lock cache
            - v1-npm-deps-{{ checksum "yarn.lock" }}
            # Fallback cache to be used
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: v1-npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: check directory
          command: ls -la ; 
      - run:
          name: check software update
          command: sudo apt-get update -y ;
      - run:
          name: Build for current environment.
          command: yarn build
          build:
      - add_ssh_keys:
          fingerprints:
            - "e7:7c:3c:ea:31:01:27:f2:da:7d:e1:0f:6b:65:47:59"
      - run:
          name: deploy
          command: ssh -o StrictHostKeyChecking=no $VM_USERNAME@$VM_PUB_IP 
                   "cd frontend_eduvalor ;
                   ls -la ;
                   git checkout dev2 ;
                   git branch ;
                   git pull origin dev2 ; 
                   rm -rf .env ; 
                   touch .env ; 
                   echo 'VUE_APP_BACKEND_API=$VUE_APP_BACKEND_API' >> .env ;
                   chmod +x ./deploy_dev.sh ; 
                   ./deploy_dev.sh"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - development:
          filters:
            branches:
              only: dev2

